# Generated by Django 5.2.16 on 2026-07-13 04:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0005_alter_customer_status'),
        ('users', '0016_companysettings_default_warranty_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('zalo', 'Zalo'), ('facebook', 'Facebook')], db_index=True, default='zalo', max_length=20, verbose_name='Nền tảng')),
                ('social_id', models.CharField(help_text='Zalo User ID hoặc Facebook PSID.', max_length=255, verbose_name='Social ID (UID)')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='Tên hiển thị')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='Ảnh đại diện')),
                ('last_message', models.TextField(blank=True, help_text='Preview tin nhắn cuối cùng từ khách.', verbose_name='Tin nhắn cuối')),
                ('last_interaction_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Lần tương tác cuối')),
                ('status', models.CharField(choices=[('new', 'Mới'), ('chatting', 'Đang chat'), ('converted', 'Đã chuyển đổi'), ('archived', 'Đã lưu trữ')], db_index=True, default='new', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú nội bộ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_social_leads', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên phụ trách')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_leads', to='users.company', verbose_name='Công ty')),
            ],
            options={
                'verbose_name': 'Social Lead',
                'verbose_name_plural': 'Social Leads',
                'ordering': ['-last_interaction_date'],
            },
        ),
        migrations.CreateModel(
            name='ZaloMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên để nhận diện mẫu trong hệ thống.', max_length=255, verbose_name='Tên mẫu (nội bộ)')),
                ('zalo_template_id', models.CharField(help_text='ID do Zalo cấp sau khi duyệt mẫu ZNS.', max_length=100, verbose_name='ID Mẫu Zalo')),
                ('template_type', models.CharField(choices=[('order_confirm', 'Xác nhận đơn hàng'), ('appointment', 'Nhắc lịch hẹn'), ('promotion', 'Khuyến mãi'), ('care', 'Chăm sóc khách hàng'), ('custom', 'Tùy chỉnh')], default='custom', max_length=20, verbose_name='Loại mẫu')),
                ('content_preview', models.TextField(blank=True, help_text='Nội dung mẫu để xem, KHÔNG dùng để gửi trực tiếp.', verbose_name='Nội dung mẫu (preview)')),
                ('params_schema', models.JSONField(default=dict, help_text='Định nghĩa các tham số. VD: {"customer_name": "Họ tên KH", "order_id": "Mã đơn hàng"}', verbose_name='Tham số mẫu')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zalo_message_templates', to='users.company', verbose_name='Công ty')),
            ],
            options={
                'verbose_name': 'Mẫu ZNS',
                'verbose_name_plural': 'Mẫu ZNS',
            },
        ),
        migrations.CreateModel(
            name='ZaloMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='SĐT nhận ZNS')),
                ('recipient_zalo_id', models.CharField(blank=True, max_length=255, verbose_name='Zalo ID người nhận')),
                ('params_sent', models.JSONField(default=dict, verbose_name='Tham số đã gửi')),
                ('status', models.CharField(choices=[('pending', 'Đang gửi'), ('sent', 'Đã gửi thành công'), ('failed', 'Gửi thất bại')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái')),
                ('zalo_msg_id', models.CharField(blank=True, help_text='ID tin nhắn do Zalo trả về sau khi gửi thành công.', max_length=255, verbose_name='Zalo Message ID')),
                ('error_message', models.TextField(blank=True, verbose_name='Thông báo lỗi')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm gửi')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zalo_message_logs', to='users.company', verbose_name='Công ty')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zalo_message_logs', to='crm.customer', verbose_name='Khách hàng')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zalo_sent_logs', to=settings.AUTH_USER_MODEL, verbose_name='Người gửi')),
                ('social_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='zalo_integration.sociallead', verbose_name='Social Lead')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='zalo_integration.zalomessagetemplate', verbose_name='Mẫu ZNS')),
            ],
            options={
                'verbose_name': 'Lịch sử gửi ZNS',
                'verbose_name_plural': 'Lịch sử gửi ZNS',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ZaloOaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oa_name', models.CharField(help_text='Tên hiển thị của Official Account trên Zalo.', max_length=255, verbose_name='Tên Zalo OA')),
                ('app_id', models.CharField(help_text='App ID lấy từ trang Zalo Developers.', max_length=100, verbose_name='App ID')),
                ('secret_key', models.CharField(help_text='Secret key lấy từ trang Zalo Developers.', max_length=255, verbose_name='App Secret')),
                ('oa_id', models.CharField(blank=True, help_text='ID của Official Account sau khi xác thực.', max_length=100, verbose_name='OA ID')),
                ('access_token', models.TextField(blank=True, null=True, verbose_name='Access Token')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='Refresh Token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm Token hết hạn')),
                ('webhook_secret', models.CharField(blank=True, help_text='Dùng để xác minh chữ ký request từ Zalo.', max_length=255, verbose_name='Webhook Secret')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zalo_oa_config', to='users.company', verbose_name='Công ty')),
            ],
            options={
                'verbose_name': 'Cấu hình Zalo OA',
                'verbose_name_plural': 'Cấu hình Zalo OA',
            },
        ),
        migrations.AddField(
            model_name='sociallead',
            name='oa_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_leads', to='zalo_integration.zalooaconfig', verbose_name='Zalo OA'),
        ),
        migrations.AddConstraint(
            model_name='zalomessagetemplate',
            constraint=models.UniqueConstraint(fields=('company', 'zalo_template_id'), name='unique_zns_template_per_company'),
        ),
        migrations.AddConstraint(
            model_name='sociallead',
            constraint=models.UniqueConstraint(fields=('company', 'platform', 'social_id'), name='unique_social_lead_per_platform_company'),
        ),
    ]
