# Generated by Django 5.2.16 on 2026-07-13 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_companysettings_default_warranty_content_and_more'),
        ('zalo_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zalomessagelog',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Lịch sử gửi ZNS', 'verbose_name_plural': 'Lịch sử ZNS'},
        ),
        migrations.AddField(
            model_name='zalooaconfig',
            name='auto_send_delivery_zns',
            field=models.BooleanField(default=False, help_text='Tự động bắn ZNS mẫu warranty kèm Phiếu bảo hành khi Đơn hàng hoàn thành.', verbose_name='Tự động gửi ZNS khi Hoàn thành Đơn'),
        ),
        migrations.AddField(
            model_name='zalooaconfig',
            name='auto_send_payment_zns',
            field=models.BooleanField(default=False, help_text='Tự động bắn ZNS mẫu payment_receipt khi Phiếu thu được ghi nhận.', verbose_name='Tự động gửi ZNS khi Thu tiền'),
        ),
        migrations.AddField(
            model_name='zalooaconfig',
            name='lead_cleanup_days',
            field=models.IntegerField(default=30, help_text='SocialLead không tương tác sau X ngày sẽ tự động bị ẩn (archived).', verbose_name='Số ngày dọn dẹp Lead rác'),
        ),
        migrations.CreateModel(
            name='ZaloMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Khách hàng gửi'), ('outbound', 'OA gửi (Sale)')], db_index=True, max_length=20, verbose_name='Hướng tin nhắn')),
                ('content', models.TextField(blank=True, verbose_name='Nội dung tin nhắn')),
                ('attachment_url', models.URLField(blank=True, null=True, verbose_name='Link file đính kèm')),
                ('attachment_type', models.CharField(blank=True, max_length=50, verbose_name='Loại đính kèm')),
                ('zalo_msg_id', models.CharField(blank=True, max_length=255, verbose_name='Zalo Message ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zalo_messages', to='users.company', verbose_name='Công ty')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người gửi (nếu outbound)')),
                ('social_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='zalo_integration.sociallead', verbose_name='Social Lead')),
            ],
            options={
                'verbose_name': 'Tin nhắn Zalo',
                'verbose_name_plural': 'Tin nhắn Zalo',
                'ordering': ['created_at'],
            },
        ),
    ]
