# Generated by Django 5.2.16 on 2026-07-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalo_integration', '0002_alter_zalomessagelog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zalooaconfig',
            name='auto_send_birthday_zns',
            field=models.BooleanField(default=False, help_text='Tự động bắn ZNS mẫu birthday vào ngày sinh nhật của Khách hàng.', verbose_name='Tự động gửi ZNS chúc mừng sinh nhật'),
        ),
        migrations.AlterField(
            model_name='zalomessagetemplate',
            name='template_type',
            field=models.CharField(choices=[('order_confirm', 'Xác nhận đơn hàng'), ('appointment', 'Nhắc lịch hẹn'), ('promotion', 'Khuyến mãi'), ('care', 'Chăm sóc khách hàng'), ('birthday', 'Chúc mừng sinh nhật'), ('custom', 'Tùy chỉnh')], default='custom', max_length=20, verbose_name='Loại mẫu'),
        ),
    ]
