# Generated by Django 5.2.15 on 2026-07-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalo_integration', '0003_zalooaconfig_auto_send_birthday_zns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallead',
            name='has_unread_message',
            field=models.BooleanField(default=False, verbose_name='Có tin nhắn chưa đọc'),
        ),
    ]
