# Generated by Django 5.2.15 on 2026-07-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalo_integration', '0004_sociallead_has_unread_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='zalooaconfig',
            name='use_system_config',
            field=models.BooleanField(default=True, help_text='Nếu bật, hệ thống sẽ dùng App ID, Secret Key từ Cấu hình Hệ thống (SuperAdmin).', verbose_name='Sử dụng cấu hình ứng dụng hệ thống'),
        ),
        migrations.AlterField(
            model_name='zalomessagetemplate',
            name='template_type',
            field=models.CharField(choices=[('order_confirm', 'Xác nhận đơn hàng'), ('appointment', 'Nhắc lịch hẹn'), ('promotion', 'Khuyến mãi'), ('care', 'Chăm sóc khách hàng'), ('birthday', 'Chúc mừng sinh nhật'), ('delivery_warranty', 'Giao hàng / Bảo hành'), ('custom', 'Tùy chỉnh')], default='custom', max_length=20, verbose_name='Loại mẫu'),
        ),
        migrations.AlterField(
            model_name='zalooaconfig',
            name='app_id',
            field=models.CharField(blank=True, help_text='App ID lấy từ trang Zalo Developers.', max_length=100, null=True, verbose_name='App ID'),
        ),
        migrations.AlterField(
            model_name='zalooaconfig',
            name='secret_key',
            field=models.CharField(blank=True, help_text='Secret key lấy từ trang Zalo Developers.', max_length=255, null=True, verbose_name='App Secret'),
        ),
        migrations.AlterField(
            model_name='zalooaconfig',
            name='webhook_secret',
            field=models.CharField(blank=True, help_text='Dùng để xác minh chữ ký request từ Zalo.', max_length=255, null=True, verbose_name='Webhook Secret'),
        ),
    ]
