# Generated by Django 5.2.16 on 2026-07-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalo_integration', '0005_zalooaconfig_use_system_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallead',
            name='detected_phone',
            field=models.CharField(blank=True, help_text='SĐT phát hiện tự động trong tin nhắn của khách.', max_length=20, verbose_name='Số điện thoại phát hiện'),
        ),
        migrations.AddField(
            model_name='sociallead',
            name='is_customer_converted',
            field=models.BooleanField(default=False, help_text='Đánh dấu True nếu SĐT này đã có hoặc đã được thêm vào Customer hệ thống.', verbose_name='Đã thêm vào Khách hàng'),
        ),
        migrations.AddField(
            model_name='zalooaconfig',
            name='auto_create_customer_from_phone',
            field=models.BooleanField(default=False, help_text='Tự động quét tin nhắn Zalo, nếu khách hàng gửi SĐT sẽ tự động chuyển đổi thành Khách hàng hệ thống.', verbose_name='Tự động quét & tạo Khách hàng khi có SĐT trong hội thoại'),
        ),
    ]
