# Generated by Django 5.2.16 on 2026-07-14 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_systemsettings_zalo_app_id_and_more'),
        ('zalo_integration', '0006_sociallead_detected_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zalooaconfig',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zalo_oa_configs', to='users.company', verbose_name='Công ty'),
        ),
    ]
