# Generated by Django 5.2.15 on 2026-07-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalo_integration', '0007_alter_zalooaconfig_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallead',
            name='unread_count',
            field=models.IntegerField(default=0, verbose_name='Số tin nhắn chưa đọc'),
        ),
    ]
