# Generated by Django 5.2.15 on 2026-07-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalo_integration', '0008_sociallead_unread_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallead',
            name='detected_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa chỉ tự động quét'),
        ),
        migrations.AddField(
            model_name='sociallead',
            name='detected_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email tự động quét'),
        ),
    ]
