# Generated by Django 5.2.16 on 2026-07-16 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_facebook_webhook_secret_system_config'),
        ('zalo_integration', '0009_sociallead_detected_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallead',
            name='is_starred',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Đánh dấu Khách VIP / Gấp'),
        ),
        migrations.CreateModel(
            name='ZaloLeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='zalo_integration.sociallead', verbose_name='Hội thoại Zalo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên ghi chú')),
            ],
            options={
                'verbose_name': 'Ghi chú nội bộ Zalo',
                'verbose_name_plural': 'Ghi chú nội bộ Zalo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZaloLeadTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên nhãn')),
                ('color', models.CharField(default='#3b82f6', max_length=20, verbose_name='Màu sắc (HEX)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zalo_lead_tags', to='users.company', verbose_name='Công ty')),
            ],
            options={
                'verbose_name': 'Nhãn hội thoại Zalo',
                'verbose_name_plural': 'Nhãn hội thoại Zalo',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='sociallead',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='social_leads', to='zalo_integration.zaloleadtag', verbose_name='Nhãn hội thoại'),
        ),
        migrations.CreateModel(
            name='ZaloQuickReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcut', models.CharField(blank=True, max_length=50, verbose_name='Cú pháp gõ tắt (vd: /banggia)')),
                ('title', models.CharField(max_length=100, verbose_name='Tiêu đề mẫu tin')),
                ('content', models.TextField(verbose_name='Nội dung tin nhắn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zalo_quick_replies', to='users.company', verbose_name='Công ty')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Tin nhắn mẫu Zalo',
                'verbose_name_plural': 'Tin nhắn mẫu Zalo',
                'ordering': ['title'],
            },
        ),
    ]
