# Generated by Django 5.2.16 on 2026-07-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalo_integration', '0010_sociallead_is_starred_zaloleadnote_zaloleadtag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zalooaconfig',
            name='request_email_template',
            field=models.TextField(blank=True, default='Xin chào quý khách! Để thuận tiện gửi thông tin và tài liệu, xin vui lòng chia sẻ địa chỉ Email của quý khách tại đây ạ.', verbose_name='Mẫu tin nhắn xin Email'),
        ),
        migrations.AddField(
            model_name='zalooaconfig',
            name='request_phone_template',
            field=models.TextField(blank=True, default='Vui lòng chia sẻ số điện thoại để chúng tôi có thể liên hệ hỗ trợ tốt nhất.', verbose_name='Mẫu tin nhắn xin SĐT'),
        ),
    ]
