# Generated by Django 5.2.16 on 2026-07-24 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0001_initial'),
        ('zalo_integration', '0011_zalooaconfig_request_email_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallead',
            name='is_ai_active',
            field=models.BooleanField(default=True, help_text='Cờ bật/tắt AI cho cuộc hội thoại này. Tắt nếu Sale thật nhảy vào.', verbose_name='AI đang tiếp quản'),
        ),
        migrations.AddField(
            model_name='zalooaconfig',
            name='ai_agent',
            field=models.ForeignKey(blank=True, help_text='AI được gán để quản lý OA này', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_agents.aiagent', verbose_name='Trợ lý AI'),
        ),
    ]
