# Generated by Django 5.2.16 on 2026-07-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalo_integration', '0012_sociallead_is_ai_active_zalooaconfig_ai_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='zalooaconfig',
            name='is_ai_active',
            field=models.BooleanField(default=True, help_text='Cờ bật/tắt AI cho toàn bộ Zalo OA này.', verbose_name='Bật/Tắt AI toàn cục'),
        ),
    ]
