# Generated by Django 5.2.15 on 2026-07-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalo_integration', '0013_zalooaconfig_is_ai_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallead',
            name='ai_summary',
            field=models.TextField(blank=True, null=True, verbose_name='AI tóm tắt hội thoại'),
        ),
    ]
