# Generated by Django 5.2.16 on 2026-07-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalo_integration', '0014_sociallead_ai_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallead',
            name='ai_tags',
            field=models.JSONField(blank=True, null=True, verbose_name='AI Tags'),
        ),
    ]
