# Generated by Django 5.2.16 on 2026-07-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalo_integration', '0015_sociallead_ai_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallead',
            name='has_ai_followed_up',
            field=models.BooleanField(default=False, verbose_name='Đã được AI bám đuổi'),
        ),
    ]
