# Generated by Django 5.2.16 on 2026-07-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalo_integration', '0016_sociallead_has_ai_followed_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='zalomessage',
            name='payload',
            field=models.JSONField(blank=True, null=True, verbose_name='Dữ liệu mở rộng (Carousel/JSON)'),
        ),
    ]
