# Generated by Django 5.2.16 on 2026-08-03 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zalo_integration', '0017_zalomessage_payload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZaloTokenRefreshLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Thành công'), ('failed', 'Thất bại')], max_length=10)),
                ('trigger', models.CharField(choices=[('auto', 'Tự động (Celery)'), ('manual', 'Thủ công (Bấm nút)'), ('oauth', 'Đăng nhập lấy Token mới')], default='auto', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('old_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Hạn cũ')),
                ('new_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Hạn mới')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm')),
                ('oa_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_refresh_logs', to='zalo_integration.zalooaconfig', verbose_name='Zalo OA')),
            ],
            options={
                'verbose_name': 'Log Refresh Token',
                'verbose_name_plural': 'Log Refresh Token',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['oa_config', '-created_at'], name='zalo_integr_oa_conf_3cab84_idx')],
            },
        ),
    ]
