# Generated by Django 5.2.15 on 2026-07-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order_new', 'Đơn hàng mới cần duyệt'), ('order_approved', 'Đơn hàng đã được duyệt'), ('order_rejected', 'Đơn hàng bị từ chối'), ('crm_assigned', 'Được phân công khách hàng mới'), ('system_update', 'Cập nhật từ hệ thống'), ('inventory_low', 'Cảnh báo tồn kho thấp')], db_index=True, max_length=30, verbose_name='Loại thông báo')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('link', models.CharField(blank=True, help_text='URL điều hướng khi click vào thông báo. VD: /orders/123', max_length=255, verbose_name='Liên kết điều hướng')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Đã đọc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-created_at'],
            },
        ),
    ]
