# Generated by Django 5.2.16 on 2026-07-22 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        ('users', '0023_companysettings_inactive_days_threshold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('is_all_company', models.BooleanField(default=True, verbose_name='Gửi toàn công ty')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='users.company', verbose_name='Công ty')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('departments', models.ManyToManyField(blank=True, related_name='announcements', to='users.department', verbose_name='Phòng ban nhận')),
            ],
            options={
                'verbose_name': 'Thông báo nội bộ',
                'verbose_name_plural': 'Thông báo nội bộ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian đọc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_announcements_status', to=settings.AUTH_USER_MODEL)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='notifications.internalannouncement')),
            ],
            options={
                'verbose_name': 'Trạng thái đọc thông báo',
                'verbose_name_plural': 'Trạng thái đọc thông báo',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='announcements/', verbose_name='File đính kèm')),
                ('file_name', models.CharField(max_length=255, verbose_name='Tên file')),
                ('file_size', models.IntegerField(default=0, verbose_name='Kích thước (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='notifications.internalannouncement')),
            ],
            options={
                'verbose_name': 'File đính kèm thông báo',
                'verbose_name_plural': 'File đính kèm thông báo',
            },
        ),
        migrations.AddIndex(
            model_name='internalannouncement',
            index=models.Index(fields=['company', 'created_at'], name='notificatio_company_7eb989_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='announcementread',
            unique_together={('announcement', 'user')},
        ),
    ]
