# Generated by Django 5.2.16 on 2026-07-22 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_internalannouncement_announcementread_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internalannouncement',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Đã ghim'),
        ),
        migrations.AddField(
            model_name='internalannouncement',
            name='priority',
            field=models.CharField(choices=[('low', 'Thấp'), ('normal', 'Thường'), ('high', 'Cao')], default='normal', max_length=20, verbose_name='Độ ưu tiên'),
        ),
        migrations.AddField(
            model_name='internalannouncement',
            name='target_users',
            field=models.ManyToManyField(blank=True, related_name='targeted_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên nhận'),
        ),
    ]
