# Generated by Django 5.2.15 on 2026-07-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_internalannouncement_is_pinned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalannouncement',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Loại thông báo'),
        ),
    ]
