# Generated by Django 5.2.16 on 2026-07-23 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_internalannouncement_category'),
        ('users', '0023_companysettings_inactive_days_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên loại thông báo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_categories', to='users.company', verbose_name='Công ty')),
            ],
            options={
                'verbose_name': 'Loại thông báo nội bộ',
                'verbose_name_plural': 'Loại thông báo nội bộ',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
    ]
