# Generated by Django 5.2.15 on 2026-07-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Format: [PREFIX]-[YYYYMMDD]-[SEQ], VD: DH-20240101-001', max_length=50, verbose_name='Mã đơn hàng')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã chấp thuận'), ('rejected', 'Đã từ chối'), ('cancelled', 'Đã hủy'), ('completed', 'Hoàn thành')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Ngày lắp đặt')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng chiết khấu')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng tiền')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm duyệt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Tên sản phẩm (snapshot)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Đơn giá (snapshot)')),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chiều rộng (m)')),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chiều cao (m)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Chiết khấu (%)')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Thành tiền')),
            ],
            options={
                'verbose_name': 'Dòng đơn hàng',
                'verbose_name_plural': 'Dòng đơn hàng',
            },
        ),
    ]
