# Generated by Django 5.2.15 on 2026-07-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='financial_status',
            field=models.CharField(choices=[('unpaid', 'Chờ thanh toán / Chờ cọc'), ('deposit_paid', 'Đã cọc (Đủ ĐK sản xuất)'), ('fully_paid', 'Đã thanh toán đủ (Đủ ĐK xuất kho)'), ('credit_approved', 'Duyệt xuất nợ ngoại lệ')], db_index=True, default='unpaid', max_length=30, verbose_name='Trạng thái tài chính'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_term',
            field=models.CharField(default='Cọc 30% - Giao hàng 70%', max_length=150, verbose_name='Mẫu thanh toán'),
        ),
    ]
