# Generated by Django 5.2.15 on 2026-07-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_financial_status_order_payment_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Diện tích (m2)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu tùy chỉnh khác (công thức, quy cách...)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chiều dài (m)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ghi chú dòng'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_image',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='URL hình ảnh sản phẩm'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='spec',
            field=models.CharField(blank=True, max_length=255, verbose_name='Quy cách / Mô tả'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='thickness',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chiều dày / Dày (mm/cm/m)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='warranty',
            field=models.CharField(blank=True, max_length=100, verbose_name='Thời gian bảo hành'),
        ),
    ]
