# Generated by Django 5.2.15 on 2026-07-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payment_terms_schedule_order_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu mở rộng theo mẫu'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.TextField(blank=True, verbose_name='Thời gian giao hàng dự kiến'),
        ),
        migrations.AddField(
            model_name='order',
            name='installation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Chi phí lắp đặt'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Chi phí vận chuyển'),
        ),
        migrations.AddField(
            model_name='order',
            name='validity_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Hiệu lực (ngày)'),
        ),
    ]
