# Generated by Django 5.2.15 on 2026-07-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_custom_data_order_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='warranty_months',
            field=models.IntegerField(default=12, verbose_name='Số tháng bảo hành'),
        ),
    ]
