# Generated by Django 5.2.15 on 2026-07-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_warranty_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã được duyệt'), ('rejected', 'Đã từ chối'), ('cancelled', 'Đã hủy'), ('completed', 'Hoàn thành')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
