# Generated by Django 5.2.15 on 2026-07-09 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0013_companysettings_active_modules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề yêu cầu')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả / Ghi chú')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('canceled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='users.company', verbose_name='Công ty')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người yêu cầu')),
            ],
            options={
                'verbose_name': 'Yêu cầu phê duyệt',
                'verbose_name_plural': 'Yêu cầu phê duyệt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField(default=1, verbose_name='Thứ tự duyệt (Cấp)')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đồng ý'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái bước này')),
                ('comments', models.TextField(blank=True, verbose_name='Ý kiến phản hồi')),
                ('acted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian thực hiện')),
                ('approver_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_tasks', to='users.role', verbose_name='Vai trò duyệt (bất kỳ ai có role này)')),
                ('approver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt chỉ định')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approvals.approvalrequest', verbose_name='Yêu cầu')),
            ],
            options={
                'verbose_name': 'Bước phê duyệt',
                'verbose_name_plural': 'Bước phê duyệt',
                'ordering': ['request', 'step_order'],
            },
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['content_type', 'object_id'], name='approvals_a_content_39fd3d_idx'),
        ),
    ]
