# Generated by Django 5.2.15 on 2026-07-09 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='acted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_approval_steps', to=settings.AUTH_USER_MODEL, verbose_name='Người thực tế duyệt'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Ý kiến phản hồi'),
        ),
    ]
