# Generated by Django 5.2.15 on 2026-07-11 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0005_alter_customer_status'),
        ('orders', '0006_order_custom_data_order_delivery_time_and_more'),
        ('users', '0015_companysettings_custom_order_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_code', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Mã giao hàng')),
                ('status', models.CharField(choices=[('pending', 'Chờ giao hàng'), ('in_transit', 'Đang giao'), ('delivered', 'Giao thành công'), ('failed', 'Giao thất bại')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái')),
                ('shipper_name', models.CharField(blank=True, max_length=150, verbose_name='Người giao hàng')),
                ('shipper_phone', models.CharField(blank=True, max_length=20, verbose_name='SĐT người giao')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Địa chỉ giao hàng')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Ngày dự kiến giao')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='Ngày giao thực tế')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='users.company', verbose_name='Công ty')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_order', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Lệnh giao hàng',
                'verbose_name_plural': 'Lệnh giao hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_code', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Mã bảo hành')),
                ('status', models.CharField(choices=[('active', 'Đang hiệu lực'), ('expired', 'Hết hạn'), ('void', 'Đã hủy/Vô hiệu')], db_index=True, default='active', max_length=20, verbose_name='Trạng thái')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('terms', models.TextField(blank=True, verbose_name='Điều khoản bảo hành')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_cards', to='users.company', verbose_name='Công ty')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_cards', to='crm.customer', verbose_name='Khách hàng')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_card', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Phiếu bảo hành',
                'verbose_name_plural': 'Phiếu bảo hành',
                'ordering': ['-created_at'],
            },
        ),
    ]
