# Generated by Django 5.2.15 on 2026-07-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliveryorder_shipper_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantycard',
            name='warranty_content',
            field=models.TextField(blank=True, verbose_name='Nội dung bảo hành'),
        ),
        migrations.AddField(
            model_name='warrantycard',
            name='warranty_rules',
            field=models.TextField(blank=True, verbose_name='Quy định bảo hành'),
        ),
    ]
