# Generated by Django 5.2.16 on 2026-07-24 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0025_companysettings_is_website_integration_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Google Gemini')], default='openai', max_length=50)),
                ('api_key', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Độ ưu tiên (cao hơn sẽ được chọn trước)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AiAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ví dụ: AI CSKH Zalo, AI Chốt Sale Fanpage', max_length=100)),
                ('model_name', models.CharField(choices=[('gpt-4o-mini', 'GPT-4o-mini (Nhanh, Rẻ)'), ('gpt-4o', 'GPT-4o (Thông minh nhất)'), ('claude-3-5-sonnet', 'Claude 3.5 Sonnet (Logic cao)'), ('gemini-1.5-flash', 'Gemini 1.5 Flash (Xử lý đa phương tiện)')], default='gpt-4o-mini', max_length=50)),
                ('system_prompt', models.TextField(blank=True, help_text='Nhân cách và hướng dẫn hành vi cho AI')),
                ('temperature', models.FloatField(default=0.7, help_text='Độ sáng tạo (0 - 1)')),
                ('enable_human_typing', models.BooleanField(default=False, verbose_name='Giả lập gõ phím')),
                ('enable_auto_summary', models.BooleanField(default=True, verbose_name='Tóm tắt hội thoại cho Sale')),
                ('enable_auto_tagging', models.BooleanField(default=False, verbose_name='Tự động gắn thẻ Inbox')),
                ('enable_drip_followup', models.BooleanField(default=False, verbose_name='Tự động bám đuổi (Follow-up 24h)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_agents', to='users.company')),
            ],
        ),
        migrations.CreateModel(
            name='AiKnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Nội dung văn bản (hoặc trích xuất từ file)')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='ai_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_docs', to='ai_agents.aiagent')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_system_keys', models.BooleanField(default=True, help_text='Sử dụng quota của hệ thống')),
                ('custom_openai_key', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_anthropic_key', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_gemini_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to='users.company')),
            ],
        ),
    ]
