# Generated by Django 5.2.15 on 2026-07-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaisettings',
            name='allow_system_keys',
            field=models.BooleanField(default=False, help_text='Super Admin cấp quyền dùng Quota hệ thống'),
        ),
        migrations.AlterField(
            model_name='companyaisettings',
            name='use_system_keys',
            field=models.BooleanField(default=True, help_text='Công ty bật/tắt sử dụng Quota hệ thống'),
        ),
    ]
