# Generated by Django 5.2.15 on 2026-07-24 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0002_companyaisettings_allow_system_keys_and_more'),
        ('users', '0025_companysettings_is_website_integration_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyaisettings',
            name='custom_anthropic_key',
        ),
        migrations.RemoveField(
            model_name='companyaisettings',
            name='custom_gemini_key',
        ),
        migrations.RemoveField(
            model_name='companyaisettings',
            name='custom_openai_key',
        ),
        migrations.CreateModel(
            name='CompanyAiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Google Gemini')], default='openai', max_length=50)),
                ('api_key', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Độ ưu tiên (cao hơn sẽ được chọn trước)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_keys', to='users.company')),
            ],
        ),
    ]
