# Generated by Django 5.2.15 on 2026-07-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0003_remove_companyaisettings_custom_anthropic_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Google Gemini')], default='openai', max_length=50),
        ),
    ]
