# Generated by Django 5.2.15 on 2026-07-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0007_alter_aiagent_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiagent',
            name='model_name',
            field=models.CharField(choices=[('gpt-3.5-turbo', 'GPT-3.5 Turbo (Cơ bản, Siêu rẻ)'), ('gpt-4o-mini', 'GPT-4o-mini (Nhanh, Rẻ - Khuyên dùng CSKH)'), ('gpt-4o', 'GPT-4o (Thông minh nhất - Khuyên dùng Sale)'), ('gpt-4-turbo', 'GPT-4 Turbo (Phức tạp, Đắt)'), ('claude-3-haiku', 'Claude 3 Haiku (Siêu nhanh, Rẻ)'), ('claude-3-5-sonnet', 'Claude 3.5 Sonnet (Cân bằng, Khuyên dùng)'), ('claude-3-opus', 'Claude 3 Opus (Thông minh nhất, Đắt)'), ('gemini-2.5-flash', 'Gemini 2.5 Flash (Siêu nhanh, Rẻ nhất)'), ('gemini-2.5-pro', 'Gemini 2.5 Pro (Thông minh, Xử lý tài liệu lớn)'), ('gemini-3.5-flash', 'Gemini 3.5 Flash (Tối tân nhất)')], default='gpt-4o-mini', max_length=50),
        ),
    ]
