# Generated by Django 5.2.15 on 2026-07-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0009_alter_aiagent_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiagent',
            name='model_name',
            field=models.CharField(choices=[('gpt-4o-mini', 'GPT-4o-mini (Nhanh, Rẻ - Khuyên dùng CSKH)'), ('gpt-4o', 'GPT-4o (Thông minh, Phổ biến)'), ('gpt-4.5-turbo', 'GPT-4.5 Turbo (Nâng cấp lớn)'), ('gpt-5', 'GPT-5 (Tối tân nhất)'), ('o1-mini', 'O1 Mini (Lập luận logic nhanh)'), ('o1', 'O1 (Siêu trí tuệ)'), ('claude-3-5-sonnet', 'Claude 3.5 Sonnet (Cân bằng)'), ('claude-3-5-opus', 'Claude 3.5 Opus (Cao cấp)'), ('claude-4-sonnet', 'Claude 4 Sonnet (Thế hệ mới)'), ('claude-4-opus', 'Claude 4 Opus (Tối tân nhất)'), ('gemini-flash-latest', 'Gemini Flash Latest (Nhanh, Rẻ nhất - Khuyên dùng CSKH)'), ('gemini-pro-latest', 'Gemini Pro Latest (Thông minh, Xử lý tài liệu lớn)'), ('gemini-flash-lite-latest', 'Gemini Flash Lite Latest (Siêu nhẹ, Free Tier)')], default='gpt-4o-mini', max_length=50),
        ),
    ]
