# Generated by Django 5.2.15 on 2026-07-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0010_alter_aiagent_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiagent',
            name='model_name',
            field=models.CharField(default='gpt-4o-mini', max_length=100),
        ),
    ]
