# Generated by Django 5.2.15 on 2026-07-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0011_alter_aiagent_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='core_prompt_template',
            field=models.TextField(blank=True, help_text='Cấu trúc JSON cốt lõi của AI', null=True),
        ),
    ]
