# Generated by Django 5.2.15 on 2026-07-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0012_aiagent_core_prompt_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='drip_followup_hours',
            field=models.IntegerField(default=24, help_text='Số giờ chờ trước khi tự động bám đuổi'),
        ),
        migrations.AlterField(
            model_name='aiagent',
            name='enable_drip_followup',
            field=models.BooleanField(default=False, verbose_name='Tự động bám đuổi (Follow-up)'),
        ),
    ]
