# Generated by Django 5.2.16 on 2026-07-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0013_aiagent_drip_followup_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='debounce_delay',
            field=models.IntegerField(default=4, help_text='Thời gian chờ (giây) sau tin nhắn cuối để gộp các tin nhắn lại. Khuyên dùng: 4-15 giây', verbose_name='Thời gian chờ gộp tin (Debounce)'),
        ),
    ]
