# Generated by Django 5.2.16 on 2026-07-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0015_apiusagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiModelPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100, unique=True)),
                ('input_price_per_1m', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('output_price_per_1m', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('is_custom', models.BooleanField(default=False, help_text='Nếu True, auto-sync sẽ không ghi đè giá này.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
