# Generated by Django 5.2.16 on 2026-07-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0016_aimodelpricing'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE EXTENSION IF NOT EXISTS vector;',
            reverse_sql='DROP EXTENSION IF EXISTS vector;'
        ),
    ]
