# Generated by Django 5.2.16 on 2026-07-25 09:03

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0017_enable_pgvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiknowledgedocument',
            name='doc_type',
            field=models.CharField(choices=[('file', 'File tài liệu'), ('qa', 'Hỏi - Đáp (Q&A)')], default='file', max_length=20),
        ),
        migrations.AddField(
            model_name='aiknowledgedocument',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiknowledgedocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang học'), ('completed', 'Hoàn thành'), ('failed', 'Lỗi')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='aiknowledgedocument',
            name='content',
            field=models.TextField(blank=True, help_text='Nội dung văn bản (hoặc trích xuất từ file)'),
        ),
        migrations.CreateModel(
            name='AiKnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Nội dung đoạn text đã băm nhỏ')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='Vector embedding (VD: text-embedding-3-small)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_agents.aiknowledgedocument')),
            ],
        ),
    ]
