# Generated by Django 5.2.16 on 2026-07-25 09:45

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0018_aiknowledgedocument_doc_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiknowledgechunk',
            name='embedding_gemini',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='Vector sinh bởi Gemini', null=True),
        ),
        migrations.AddField(
            model_name='aiknowledgechunk',
            name='embedding_provider',
            field=models.CharField(default='openai', help_text='Nền tảng đã dùng để nhúng Vector', max_length=50),
        ),
        migrations.AddField(
            model_name='companyaisettings',
            name='default_embedding_provider',
            field=models.CharField(choices=[('openai', 'OpenAI (1536 chiều)'), ('gemini', 'Google Gemini (768 chiều)')], default='openai', max_length=50),
        ),
        migrations.AlterField(
            model_name='aiknowledgechunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='Vector sinh bởi OpenAI', null=True),
        ),
    ]
