# Generated by Django 5.2.16 on 2026-07-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0019_aiknowledgechunk_embedding_gemini_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiknowledgedocument',
            name='embedding_provider',
            field=models.CharField(default='openai', help_text='Nền tảng nhúng dữ liệu (openai hoặc gemini)', max_length=20),
        ),
        migrations.AddField(
            model_name='aiknowledgedocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
