# Generated by Django 5.2.16 on 2026-07-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0020_aiknowledgedocument_embedding_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaisettings',
            name='auto_sync_products',
            field=models.BooleanField(default=False, help_text='Tự động đồng bộ Sản phẩm làm Tri thức RAG'),
        ),
    ]
