# Generated by Django 5.2.16 on 2026-07-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0021_companyaisettings_auto_sync_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaisettings',
            name='enable_chat_extraction',
            field=models.BooleanField(default=True, help_text='Cho phép Đóng gói Hội thoại vào RAG'),
        ),
    ]
