# Generated by Django 5.2.16 on 2026-07-27 10:28

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0022_companyaisettings_enable_chat_extraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiknowledgedocument',
            name='image_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, help_text='Vector sinh ra nếu tải lên file ảnh (CLIP)', null=True),
        ),
    ]
