# Generated by Django 5.2.16 on 2026-07-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0023_aiknowledgedocument_image_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiknowledgedocument',
            name='doc_type',
            field=models.CharField(choices=[('file', 'File tài liệu'), ('qa', 'Hỏi - Đáp (Q&A)'), ('image', 'Hình ảnh Mẫu')], default='file', max_length=20),
        ),
    ]
