# Generated by Django 5.2.16 on 2026-07-28 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0024_alter_aiknowledgedocument_doc_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiknowledgedocument',
            name='image_vector',
        ),
    ]
