# Generated by Django 5.2.15 on 2026-07-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('source', models.CharField(choices=[('facebook', 'Facebook'), ('zalo', 'Zalo'), ('referral', 'Giới thiệu'), ('walk_in', 'Đến trực tiếp'), ('website', 'Website'), ('other', 'Khác')], default='other', max_length=20, verbose_name='Nguồn khách')),
                ('status', models.CharField(choices=[('new', 'Khách mới'), ('potential', 'Tiềm năng'), ('active', 'Đang hoạt động'), ('lost', 'Đã mất'), ('inactive', 'Không hoạt động')], default='new', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Chức vụ')),
            ],
            options={
                'verbose_name': 'Đầu mối liên hệ',
                'verbose_name_plural': 'Đầu mối liên hệ',
            },
        ),
        migrations.CreateModel(
            name='CustomerInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('call', 'Gọi điện'), ('meeting', 'Gặp mặt'), ('email', 'Gửi Email'), ('zalo', 'Nhắn Zalo'), ('quotation', 'Gửi báo giá'), ('care', 'Chăm sóc')], max_length=20, verbose_name='Hình thức')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('result', models.CharField(blank=True, choices=[('interested', 'Quan tâm'), ('not_interested', 'Không quan tâm'), ('need_follow_up', 'Cần follow-up'), ('closed', 'Đã chốt')], default='', max_length=20, verbose_name='Kết quả')),
                ('next_follow_up', models.DateTimeField(blank=True, null=True, verbose_name='Lịch follow-up tiếp theo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lịch sử chăm sóc',
                'verbose_name_plural': 'Lịch sử chăm sóc',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên tag')),
                ('color', models.CharField(default='#1649c9', help_text='Mã màu hex, vd: #FF5733', max_length=20, verbose_name='Màu sắc')),
            ],
            options={
                'verbose_name': 'Tag khách hàng',
                'verbose_name_plural': 'Tag khách hàng',
            },
        ),
    ]
