# Generated by Django 5.2.15 on 2026-07-04 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên phụ trách'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='users.company', verbose_name='Công ty'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.customer', verbose_name='Khách hàng'),
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_interactions', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện'),
        ),
        migrations.AddField(
            model_name='customerinteraction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.customer', verbose_name='Khách hàng'),
        ),
        migrations.AddField(
            model_name='customertag',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_tags', to='users.company', verbose_name='Công ty'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='customers', to='crm.customertag', verbose_name='Tags'),
        ),
        migrations.AddConstraint(
            model_name='customertag',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_customer_tag_per_company'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('company', 'phone'), name='unique_customer_phone_per_company'),
        ),
    ]
