# Generated by Django 5.2.15 on 2026-07-06 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customer_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='interactions/%Y/%m/', verbose_name='File đính kèm')),
                ('file_name', models.CharField(max_length=255, verbose_name='Tên file gốc')),
                ('file_size', models.IntegerField(default=0, verbose_name='Dung lượng (bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tải lên')),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.customerinteraction', verbose_name='Lịch sử chăm sóc')),
            ],
            options={
                'verbose_name': 'File đính kèm tương tác',
                'verbose_name_plural': 'File đính kèm tương tác',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
