# Generated by Django 5.2.15 on 2026-07-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_interactionattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('new', 'Khách mới'), ('potential', 'Tiềm năng'), ('active', 'Đang hoạt động'), ('has_order', 'Đã có đơn hàng'), ('repeat_order', 'Mua thêm đơn hàng'), ('lost', 'Đã mất'), ('inactive', 'Không hoạt động')], default='new', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
