# Generated by Django 5.2.16 on 2026-07-13 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_customer_status'),
        ('zalo_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='social_lead',
            field=models.OneToOneField(blank=True, help_text='Liên kết về SocialLead nếu khách được convert từ Zalo OA.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_customer', to='zalo_integration.sociallead', verbose_name='Social Lead (Zalo)'),
        ),
    ]
