# Generated by Django 5.2.16 on 2026-07-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_customer_social_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_inactive',
            field=models.BooleanField(default=False, verbose_name='Không hoạt động (Ngủ đông)'),
        ),
    ]
