# Generated by Django 5.2.16 on 2026-07-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_customer_is_inactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('new', 'Khách mới'), ('potential', 'Tìm hiểu nhu cầu'), ('active', 'Sắp chốt'), ('lost', 'Không còn nhu cầu'), ('has_order', 'Đã có đơn hàng'), ('repeat_order', 'Mua thêm đơn hàng')], default='new', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
