# Generated by Django 5.2.16 on 2026-07-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('zalo', 'Zalo'), ('referral', 'Giới thiệu'), ('walk_in', 'Đến trực tiếp'), ('website', 'Website'), ('other', 'Khác')], default='other', max_length=100, verbose_name='Nguồn khách'),
        ),
    ]
