# Generated by Django 5.2.16 on 2026-07-14 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0006_customer_social_lead'),
        ('users', '0017_systemsettings_zalo_app_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_user_id', models.CharField(max_length=100, verbose_name='Facebook User ID (PSID)')),
                ('fb_user_name', models.CharField(blank=True, max_length=255, verbose_name='Tên người dùng Facebook')),
                ('fb_user_avatar', models.URLField(blank=True, null=True, verbose_name='Avatar Facebook')),
                ('detected_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='SĐT đã phát hiện')),
                ('is_customer_converted', models.BooleanField(default=False, verbose_name='Đã có trong hệ thống KH')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm tin nhắn cuối')),
                ('last_message_preview', models.CharField(blank=True, max_length=255, verbose_name='Nội dung tin nhắn cuối (tóm tắt)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facebook_leads_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên phụ trách')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_leads', to='users.company', verbose_name='Công ty')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facebook_leads', to='crm.customer', verbose_name='Khách hàng CRM liên kết')),
            ],
            options={
                'verbose_name': 'Hội thoại Facebook',
                'verbose_name_plural': 'Hội thoại Facebook',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='FacebookMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_message_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Facebook Message ID')),
                ('sender_type', models.CharField(choices=[('customer', 'Khách hàng'), ('page', 'Trang Facebook (Admin)')], default='customer', max_length=20, verbose_name='Người gửi')),
                ('text', models.TextField(blank=True, verbose_name='Nội dung văn bản')),
                ('attachment_url', models.URLField(blank=True, null=True, verbose_name='Đính kèm (URL ảnh/file)')),
                ('attachment_type', models.CharField(blank=True, max_length=50, verbose_name='Loại đính kèm (image, file, sticker...)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='facebook_integration.facebooklead', verbose_name='Hội thoại')),
            ],
            options={
                'verbose_name': 'Tin nhắn Facebook',
                'verbose_name_plural': 'Tin nhắn Facebook',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacebookPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(help_text='Tên hiển thị của Fanpage trên Facebook.', max_length=255, verbose_name='Tên Trang Facebook')),
                ('page_id', models.CharField(help_text='ID của Fanpage Facebook (lấy từ trang Meta Developers).', max_length=100, verbose_name='Page ID')),
                ('page_access_token', models.TextField(blank=True, help_text='Token dài hạn (Long-Lived Page Access Token) để gửi/nhận tin nhắn.', null=True, verbose_name='Page Access Token')),
                ('webhook_verify_token', models.CharField(blank=True, help_text='Mã xác thực webhook tùy chỉnh – khai báo trên Meta Developers.', max_length=255, verbose_name='Webhook Verify Token')),
                ('page_avatar', models.URLField(blank=True, null=True, verbose_name='Avatar Trang Facebook')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang kết nối')),
                ('auto_create_customer_from_phone', models.BooleanField(default=False, help_text='Tự động tạo hồ sơ Khách hàng vào CRM khi nhận diện được SĐT trong hội thoại.', verbose_name='Tự động tạo KH khi phát hiện SĐT')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facebook_pages_managed', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên phụ trách mặc định')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_page_configs', to='users.company', verbose_name='Công ty')),
            ],
            options={
                'verbose_name': 'Cấu hình Trang Facebook',
                'verbose_name_plural': 'Cấu hình Trang Facebook',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'page_id')},
            },
        ),
        migrations.AddField(
            model_name='facebooklead',
            name='page_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='facebook_integration.facebookpageconfig', verbose_name='Trang Facebook'),
        ),
        migrations.AlterUniqueTogether(
            name='facebooklead',
            unique_together={('page_config', 'fb_user_id')},
        ),
    ]
