# Generated by Django 5.2.16 on 2026-07-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_integration', '0001_facebook_module_and_company_toggle'),
        ('users', '0018_facebook_oauth_app_config_and_token_expiry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facebookpageconfig',
            unique_together={('company', 'page_name')},
        ),
        migrations.AddField(
            model_name='facebookpageconfig',
            name='app_id',
            field=models.CharField(blank=True, help_text='Facebook App ID (chỉ cần khi không dùng cấu hình hệ thống).', max_length=100, null=True, verbose_name='App ID'),
        ),
        migrations.AddField(
            model_name='facebookpageconfig',
            name='app_secret',
            field=models.CharField(blank=True, help_text='Facebook App Secret (chỉ cần khi không dùng cấu hình hệ thống).', max_length=255, null=True, verbose_name='App Secret'),
        ),
        migrations.AddField(
            model_name='facebookpageconfig',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Thời điểm Page Access Token hết hạn. None = không hết hạn (Page Token thường vĩnh viễn).', null=True, verbose_name='Thời hạn Token'),
        ),
        migrations.AddField(
            model_name='facebookpageconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='facebookpageconfig',
            name='use_system_config',
            field=models.BooleanField(default=True, help_text='Nếu bật, hệ thống sẽ dùng App ID, Secret từ Cấu hình Hệ thống (SuperAdmin).', verbose_name='Sử dụng cấu hình ứng dụng hệ thống'),
        ),
        migrations.AlterField(
            model_name='facebookpageconfig',
            name='page_access_token',
            field=models.TextField(blank=True, help_text='Long-Lived Page Access Token để gửi/nhận tin nhắn.', null=True, verbose_name='Page Access Token'),
        ),
        migrations.AlterField(
            model_name='facebookpageconfig',
            name='page_id',
            field=models.CharField(blank=True, help_text='ID của Fanpage Facebook (tự động lấy sau khi đăng nhập).', max_length=100, verbose_name='Page ID'),
        ),
    ]
