# Generated by Django 5.2.16 on 2026-07-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_integration', '0002_facebook_oauth_app_config_and_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpageconfig',
            name='page_avatar',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Avatar Trang Facebook'),
        ),
    ]
