# Generated by Django 5.2.16 on 2026-07-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_integration', '0003_increase_page_avatar_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebooklead',
            name='fb_user_avatar',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Avatar Facebook'),
        ),
        migrations.AlterField(
            model_name='facebookmessage',
            name='attachment_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Đính kèm (URL ảnh/file)'),
        ),
    ]
