# Generated by Django 5.2.16 on 2026-07-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_integration', '0004_increase_lead_and_message_url_lengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebooklead',
            name='has_unread_message',
            field=models.BooleanField(default=False, verbose_name='Có tin nhắn chưa đọc'),
        ),
    ]
