# Generated by Django 5.2.16 on 2026-07-15 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_integration', '0005_add_has_unread_message'),
        ('users', '0019_facebook_webhook_secret_system_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facebooklead',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Đã dọn dẹp / Ẩn khỏi inbox'),
        ),
        migrations.AddField(
            model_name='facebookpageconfig',
            name='lead_cleanup_days',
            field=models.IntegerField(default=30, help_text='Hội thoại không tương tác sau X ngày sẽ tự động bị ẩn (archived).', verbose_name='Số ngày dọn dẹp Lead rác'),
        ),
        migrations.CreateModel(
            name='QuickMediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ví dụ: Bảng báo giá sỉ 2026, Hình Sâm VIP...', max_length=255, verbose_name='Tiêu đề / Tên mẫu')),
                ('media_type', models.CharField(choices=[('image', 'Hình ảnh'), ('video', 'Video'), ('file', 'Tài liệu/File')], default='image', max_length=20, verbose_name='Loại file')),
                ('file_url', models.URLField(max_length=1000, verbose_name='URL file/ảnh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_media_assets', to='users.company', verbose_name='Công ty')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Thư viện file gửi nhanh',
                'verbose_name_plural': 'Thư viện file gửi nhanh',
                'ordering': ['-created_at'],
            },
        ),
    ]
