# Generated by Django 5.2.15 on 2026-07-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_integration', '0007_facebooklead_is_starred_facebookleadnote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebooklead',
            name='unread_count',
            field=models.IntegerField(default=0, verbose_name='Số tin nhắn chưa đọc'),
        ),
    ]
