# Generated by Django 5.2.15 on 2026-07-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_integration', '0008_facebooklead_unread_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpageconfig',
            name='request_email_template',
            field=models.TextField(default='Dạ bạn cho mình xin địa chỉ Email để bên em gửi catalogue và thông tin chi tiết qua email cho mình nhé 📧', verbose_name='Mẫu tin nhắn xin Email'),
        ),
        migrations.AddField(
            model_name='facebookpageconfig',
            name='request_phone_template',
            field=models.TextField(default='Dạ chào bạn, để tiện chuyên viên tư vấn chi tiết và gửi bảng giá ưu đãi, bạn cho mình xin số điện thoại liên hệ với ạ ❤️', verbose_name='Mẫu tin nhắn xin SĐT'),
        ),
    ]
