# Generated by Django 5.2.15 on 2026-07-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_integration', '0009_facebookpageconfig_request_email_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebooklead',
            name='detected_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa chỉ tự động quét'),
        ),
        migrations.AddField(
            model_name='facebooklead',
            name='detected_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email tự động quét'),
        ),
    ]
