# Generated by Django 5.2.15 on 2026-07-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_integration', '0010_facebooklead_detected_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickmediaasset',
            name='file_url',
            field=models.CharField(blank=True, max_length=1000, verbose_name='URL file/ảnh'),
        ),
    ]
