# Generated by Django 5.2.15 on 2026-07-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_integration', '0011_alter_quickmediaasset_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickmediaasset',
            name='folder',
            field=models.CharField(default='Chung', max_length=100, verbose_name='Thư mục/Nhóm'),
        ),
    ]
