# Generated by Django 5.2.16 on 2026-07-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_integration', '0013_facebooklead_is_ai_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpageconfig',
            name='is_ai_active',
            field=models.BooleanField(default=True, help_text='Cờ bật/tắt AI cho toàn bộ trang Facebook này.', verbose_name='Bật/Tắt AI toàn cục'),
        ),
    ]
