# Generated by Django 5.2.16 on 2026-07-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_integration', '0016_facebooklead_ai_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebooklead',
            name='has_ai_followed_up',
            field=models.BooleanField(default=False, verbose_name='Đã được AI bám đuổi'),
        ),
    ]
