# Generated by Django 5.2.16 on 2026-07-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_integration', '0017_facebooklead_has_ai_followed_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookmessage',
            name='payload',
            field=models.JSONField(blank=True, null=True, verbose_name='Dữ liệu mở rộng (Carousel/JSON)'),
        ),
        migrations.AlterField(
            model_name='facebookmessage',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Loại đính kèm (image, file, carousel...)'),
        ),
    ]
