# Generated by Django 5.2.15 on 2026-07-09 07:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_financial_status_order_payment_term'),
        ('users', '0013_companysettings_active_modules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPaymentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('deposit', 'Kỳ 1: Đặt cọc (Trước sản xuất)'), ('before_delivery', 'Kỳ 2: Trước giao hàng / Xuất kho'), ('after_delivery', 'Kỳ 3: Sau giao hàng & Lắp đặt'), ('warranty', 'Kỳ 4: Giữ lại bảo hành')], default='deposit', max_length=30, verbose_name='Loại kỳ thanh toán')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề kỳ')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tỷ lệ %')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền phải thu')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Số tiền đã thu')),
                ('status', models.CharField(choices=[('pending', 'Chờ thu'), ('partial', 'Thu một phần'), ('paid', 'Đã hoàn tất')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Hạn thanh toán')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_milestones', to='users.company', verbose_name='Công ty')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_milestones', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Kỳ thanh toán đơn hàng',
                'verbose_name_plural': 'Kỳ thanh toán đơn hàng',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_code', models.CharField(max_length=50, unique=True, verbose_name='Mã phiếu thu')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền thu')),
                ('payment_method', models.CharField(choices=[('transfer', 'Chuyển khoản ngân hàng'), ('cash', 'Tiền mặt'), ('card', 'Thẻ / POS')], default='transfer', max_length=20, verbose_name='Hình thức')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày thu tiền')),
                ('reference_code', models.CharField(blank=True, max_length=100, verbose_name='Mã GD Ngân hàng')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to='users.company', verbose_name='Công ty')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Người lập phiếu')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='finance.orderpaymentmilestone', verbose_name='Kỳ thanh toán')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Phiếu thu tiền',
                'verbose_name_plural': 'Phiếu thu tiền',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
