# Generated by Django 5.2.15 on 2026-07-09 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceipt',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Ngày thu tiền'),
        ),
    ]
