# Generated by Django 5.2.15 on 2026-07-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_paymentreceipt_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='attachments',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Chứng từ đính kèm'),
        ),
    ]
