# Generated by Django 5.2.15 on 2026-07-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(help_text='VD: IMP-20240101-001, EXP-20240101-001', max_length=50, verbose_name='Mã phiếu')),
                ('type', models.CharField(choices=[('import', 'Nhập kho'), ('export', 'Xuất kho'), ('adjust', 'Điều chỉnh')], db_index=True, max_length=20, verbose_name='Loại phiếu')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='Chỉ áp dụng khi loại phiếu là Nhập kho.', max_digits=15, verbose_name='Đơn giá nhập')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Phiếu kho',
                'verbose_name_plural': 'Phiếu kho',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, verbose_name='Mã sản phẩm')),
                ('name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('unit', models.CharField(choices=[('cái', 'Cái'), ('m²', 'm²'), ('m', 'Mét'), ('bộ', 'Bộ'), ('kg', 'Kg'), ('lít', 'Lít')], default='cái', max_length=20, verbose_name='Đơn vị tính')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Giá bán')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Giá nhập')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Hình ảnh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang kinh doanh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Tên loại sản phẩm')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Loại sản phẩm',
                'verbose_name_plural': 'Loại sản phẩm',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('min_quantity', models.IntegerField(default=0, verbose_name='Ngưỡng cảnh báo tồn kho thấp')),
            ],
            options={
                'verbose_name': 'Tồn kho',
                'verbose_name_plural': 'Tồn kho',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Tên kho')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ kho')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Kho hàng',
                'verbose_name_plural': 'Kho hàng',
            },
        ),
    ]
