# Generated by Django 5.2.15 on 2026-07-09 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('users', '0013_companysettings_active_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text="vd: {'Màu sắc': 'Đỏ', 'Kích thước': 'XL'}", verbose_name='Thuộc tính biến thể'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.productcategory', verbose_name='Loại sản phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tên sản phẩm (biến thể)'),
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên thuộc tính')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='users.company', verbose_name='Công ty')),
            ],
            options={
                'verbose_name': 'Thuộc tính',
                'verbose_name_plural': 'Thuộc tính',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên mẫu sản phẩm')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('unit', models.CharField(choices=[('cái', 'Cái'), ('m²', 'm²'), ('m', 'Mét'), ('bộ', 'Bộ'), ('kg', 'Kg'), ('lít', 'Lít')], default='cái', max_length=20, verbose_name='Đơn vị tính')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/templates/', verbose_name='Hình ảnh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang kinh doanh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='inventory.productcategory', verbose_name='Loại sản phẩm')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_templates', to='users.company', verbose_name='Công ty')),
            ],
            options={
                'verbose_name': 'Mẫu sản phẩm',
                'verbose_name_plural': 'Mẫu sản phẩm',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.producttemplate', verbose_name='Thuộc mẫu sản phẩm'),
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Giá trị')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='inventory.productattribute', verbose_name='Thuộc tính')),
            ],
            options={
                'verbose_name': 'Giá trị thuộc tính',
                'verbose_name_plural': 'Giá trị thuộc tính',
                'unique_together': {('attribute', 'value')},
            },
        ),
    ]
