# Generated by Django 5.2.15 on 2026-07-10 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_attributes_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('completed', 'Hoàn thành'), ('rejected', 'Đã hủy')], default='completed', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='inventory.warehouse', verbose_name='Kho hàng'),
        ),
    ]
