# Generated by Django 5.2.16 on 2026-07-20 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventorytransaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='target_warehouse',
            field=models.ForeignKey(blank=True, help_text='Chỉ áp dụng khi loại phiếu là Điều chuyển kho.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_in_transactions', to='inventory.warehouse', verbose_name='Kho nhận'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='type',
            field=models.CharField(choices=[('import', 'Nhập kho'), ('export', 'Xuất kho'), ('adjust', 'Điều chỉnh'), ('transfer', 'Điều chuyển')], db_index=True, max_length=20, verbose_name='Loại phiếu'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='inventory.warehouse', verbose_name='Kho hàng (Kho xuất)'),
        ),
    ]
