# Generated by Django 5.2.16 on 2026-07-20 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventorytransaction_target_warehouse_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventorytransaction',
            name='unique_transaction_code_per_company',
        ),
    ]
