# Generated by Django 5.2.16 on 2026-07-21 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_inventorytransaction_unique_transaction_code_per_company'),
        ('production', '0004_factory_productionorder_factory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='factory',
            field=models.ForeignKey(blank=True, help_text='Nhà máy nhận vật tư khi xuất kho.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='production.factory', verbose_name='Nhà máy sản xuất'),
        ),
    ]
