# Generated by Django 5.2.16 on 2026-07-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_add_factory_to_inventory_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('product', 'Sản phẩm'), ('service', 'Dịch vụ / Chi phí')], default='product', max_length=20, verbose_name='Loại'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='product_type',
            field=models.CharField(choices=[('product', 'Sản phẩm'), ('service', 'Dịch vụ / Chi phí')], default='product', max_length=20, verbose_name='Loại'),
        ),
    ]
