# Generated by Django 5.2.16 on 2026-07-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('cái', 'Cái'), ('m²', 'm²'), ('m', 'Mét'), ('bộ', 'Bộ'), ('kg', 'Kg'), ('lít', 'Lít'), ('lần', 'Lần'), ('chuyến', 'Chuyến')], default='cái', max_length=20, verbose_name='Đơn vị tính'),
        ),
        migrations.AlterField(
            model_name='producttemplate',
            name='unit',
            field=models.CharField(choices=[('cái', 'Cái'), ('m²', 'm²'), ('m', 'Mét'), ('bộ', 'Bộ'), ('kg', 'Kg'), ('lít', 'Lít'), ('lần', 'Lần'), ('chuyến', 'Chuyến')], default='cái', max_length=20, verbose_name='Đơn vị tính'),
        ),
    ]
