# Generated by Django 5.2.16 on 2026-07-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_product_unit_alter_producttemplate_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='custom_product_name',
            field=models.CharField(blank=True, help_text='VD: Cửa composite CCP01 - Mẫu mới (800 x 2200 x 130)', max_length=500, null=True, verbose_name='Tên hiển thị tùy chỉnh'),
        ),
    ]
