# Generated by Django 5.2.16 on 2026-07-28 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_producttemplate_image_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttemplate',
            name='image_vector',
        ),
    ]
