# Generated by Django 5.2.16 on 2026-07-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_producttemplate_image_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='image_description',
            field=models.TextField(blank=True, help_text='Được dùng để tìm kiếm sản phẩm khi khách gửi ảnh', verbose_name='Mô tả ảnh (AI sinh ra)'),
        ),
    ]
