# Generated by Django 5.2.16 on 2026-07-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_producttemplate_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_knowledge',
            field=models.TextField(blank=True, help_text='Thông tin nội bộ dành riêng cho AI đọc để tư vấn khách hàng', verbose_name='Tài liệu huấn luyện AI'),
        ),
    ]
