# Generated by Django 5.2.16 on 2026-07-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_product_ai_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã mẫu (SKU prefix)'),
        ),
    ]
