# Generated by Django 5.2.15 on 2026-07-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên mẫu báo giá')),
                ('code', models.SlugField(unique=True, verbose_name='Mã mẫu')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('header_content', models.TextField(blank=True, verbose_name='Nội dung Header / Tiêu đề')),
                ('footer_content', models.TextField(blank=True, verbose_name='Điều khoản & Footer')),
                ('layout_style', models.CharField(default='modern_blue', max_length=50, verbose_name='Phong cách giao diện')),
                ('is_default', models.BooleanField(default=False, verbose_name='Mẫu mặc định hệ thống')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Mẫu báo giá',
                'verbose_name_plural': 'Mẫu báo giá',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
