# Generated by Django 5.2.15 on 2026-07-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_quotationtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationtemplate',
            name='layout_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Cấu hình Block Layout (Kéo thả)'),
        ),
    ]
