# Generated by Django 5.2.15 on 2026-07-07 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_quotationtemplate_layout_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu mở rộng theo mẫu'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=255, verbose_name='Thời gian giao hàng dự kiến'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='installation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Chi phí lắp đặt'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=255, verbose_name='Điều khoản thanh toán'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Chi phí vận chuyển'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_quotations', to='sales.quotationtemplate', verbose_name='Mẫu báo giá sử dụng'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='validity_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Hiệu lực báo giá (ngày)'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Diện tích (m²)'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dữ liệu mở rộng dòng'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chiều dài (m)'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='spec',
            field=models.CharField(blank=True, max_length=255, verbose_name='Quy cách / Mô tả'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='warranty',
            field=models.CharField(blank=True, max_length=100, verbose_name='Thời gian bảo hành'),
        ),
    ]
