# Generated by Django 5.2.15 on 2026-07-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_quotation_custom_data_quotation_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='product_image',
            field=models.CharField(blank=True, max_length=500, verbose_name='Hình ảnh sản phẩm (snapshot URL)'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='thickness',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chiều dày / Dày (mm/cm/m)'),
        ),
    ]
