# Generated by Django 5.2.15 on 2026-07-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_quotationitem_product_image_quotationitem_thickness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='delivery_time',
            field=models.TextField(blank=True, verbose_name='Thời gian giao hàng dự kiến'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='payment_terms',
            field=models.TextField(blank=True, verbose_name='Điều khoản thanh toán'),
        ),
    ]
