# Generated by Django 5.2.15 on 2026-07-09 03:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('sales', '0007_alter_quotation_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='order',
            field=models.OneToOneField(blank=True, help_text='Đơn hàng được sinh ra sau khi duyệt báo giá', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_quotation', to='orders.order', verbose_name='Đơn hàng liên kết'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Dùng để tạo link public cho khách ký online', unique=True, verbose_name='Token Public'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='quotations/signatures/', verbose_name='Chữ ký khách hàng'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian ký'),
        ),
    ]
