# Generated by Django 5.2.15 on 2026-07-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_quotation_order_quotation_public_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='customer_name_signed',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên người ký'),
        ),
    ]
