# Generated by Django 5.2.15 on 2026-07-09 04:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_quotation_customer_name_signed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token Public'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='signature_image',
            field=models.TextField(blank=True, null=True, verbose_name='Chữ ký khách hàng (Base64)'),
        ),
    ]
