# Generated by Django 5.2.15 on 2026-07-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_quotation_public_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('pending_approval', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('sent', 'Đã gửi'), ('accepted', 'Đã chấp nhận'), ('rejected', 'Đã từ chối')], default='draft', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
