# Generated by Django 5.2.15 on 2026-07-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_quotation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='public_link_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hết hạn Link Public'),
        ),
    ]
