# Generated by Django 5.2.15 on 2026-07-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_quotation_public_link_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='payment_terms_schedule',
            field=models.JSONField(blank=True, default=list, verbose_name='Tiến độ thanh toán'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng trước thuế (Subtotal)'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tiền thuế VAT'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Thuế VAT'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='payment_terms',
            field=models.TextField(blank=True, verbose_name='Điều khoản thanh toán (Text)'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng cộng sau thuế'),
        ),
    ]
