# Generated by Django 5.2.15 on 2026-07-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_quotation_payment_terms_schedule_quotation_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='warranty_months',
            field=models.IntegerField(default=12, verbose_name='Số tháng bảo hành'),
        ),
    ]
