# Generated by Django 5.2.16 on 2026-07-23 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_product_product_type_producttemplate_product_type'),
        ('sales', '0014_quotation_warranty_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='item_type',
            field=models.CharField(choices=[('product', 'Sản phẩm'), ('service', 'Dịch vụ / Chi phí')], default='product', max_length=20, verbose_name='Loại item'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='inventory.product', verbose_name='Sản phẩm'),
        ),
    ]
