# Generated by Django 5.2.15 on 2026-07-04 02:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên công ty')),
                ('workspace_id', models.SlugField(help_text='Mã định danh công ty khi đăng nhập (vd: ANPHAT). Tự động tạo từ mã số thuế nếu để trống.', max_length=60, unique=True, verbose_name='Workspace ID')),
                ('tax_code', models.CharField(max_length=50, unique=True, verbose_name='Mã số thuế')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại công ty')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo công ty')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('user_limit', models.PositiveIntegerField(blank=True, help_text='Số tài khoản nhân viên tối đa. Để trống = không giới hạn.', null=True, verbose_name='Giới hạn nhân viên')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Công ty',
                'verbose_name_plural': 'Công ty',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Mã quyền')),
                ('name', models.CharField(max_length=150, verbose_name='Tên quyền')),
                ('module', models.CharField(blank=True, default='', help_text='Tên module chứa quyền này (vd: crm, sales, inventory...)', max_length=50, verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Quyền',
                'verbose_name_plural': 'Quyền',
                'ordering': ['module', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_prefix', models.CharField(default='DH', help_text="VD: 'DH' → Mã đơn: DH-20240101-001", max_length=10, verbose_name='Tiền tố mã đơn hàng')),
                ('lead_routing', models.CharField(choices=[('manual', 'Thủ công (Trưởng phòng gán)'), ('round_robin', 'Tự động Round-robin')], default='manual', max_length=20, verbose_name='Phương thức phân bổ Lead')),
                ('timezone', models.CharField(default='Asia/Ho_Chi_Minh', max_length=50, verbose_name='Múi giờ')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='users.company', verbose_name='Công ty')),
            ],
            options={
                'verbose_name': 'Cấu hình công ty',
                'verbose_name_plural': 'Cấu hình công ty',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Tên vai trò')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='users.company', verbose_name='Công ty')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='users.permission', verbose_name='Danh sách quyền')),
            ],
            options={
                'verbose_name': 'Vai trò',
                'verbose_name_plural': 'Vai trò',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('job_title', models.CharField(blank=True, help_text='Chức danh hiển thị (vd: Giám đốc kinh doanh, Kế toán trưởng...)', max_length=150, verbose_name='Chức danh')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện')),
                ('is_company_admin', models.BooleanField(default=False, help_text='Tài khoản quản trị cao nhất của công ty (Owner/Giám đốc). Có toàn quyền trong công ty.', verbose_name='Là Admin công ty')),
                ('department_id', models.IntegerField(blank=True, null=True, verbose_name='Phòng ban')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.company', verbose_name='Công ty')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.role', verbose_name='Vai trò')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_role_name_per_company'),
        ),
    ]
