# Generated by Django 5.2.15 on 2026-07-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_strong_password', models.BooleanField(default=False, help_text='Bắt buộc toàn hệ thống dùng mật khẩu mạnh (chữ hoa, chữ thường, số, ký tự đặc biệt).', verbose_name='Yêu cầu mật khẩu mạnh')),
            ],
            options={
                'verbose_name': 'Cấu hình Hệ thống',
                'verbose_name_plural': 'Cấu hình Hệ thống',
            },
        ),
    ]
