# Generated by Django 5.2.15 on 2026-07-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='enable_public_registration',
            field=models.BooleanField(default=True, help_text='Bật/tắt tính năng đăng ký doanh nghiệp mới trên hệ thống.', verbose_name='Cho phép đăng ký mới'),
        ),
    ]
