# Generated by Django 5.2.15 on 2026-07-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_systemsettings_enable_public_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='default_plan',
            field=models.CharField(default='starter', max_length=50, verbose_name='Gói mặc định'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_user_limit',
            field=models.IntegerField(default=5, verbose_name='Số tài khoản mặc định'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='jwt_expiration_hours',
            field=models.IntegerField(default=24, verbose_name='Thời gian hết hạn JWT'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_file_upload_mb',
            field=models.IntegerField(default=25, verbose_name='Dung lượng tải file tối đa'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='tenant_isolation_mode',
            field=models.CharField(default='strict', max_length=50, verbose_name='Chế độ cô lập dữ liệu'),
        ),
    ]
