# Generated by Django 5.2.15 on 2026-07-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_systemsettings_default_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã gói')),
                ('name', models.CharField(max_length=150, verbose_name='Tên gói')),
                ('user_limit', models.IntegerField(help_text='Nhập 99999 cho Không giới hạn', verbose_name='Giới hạn người dùng')),
                ('is_default', models.BooleanField(default=False, verbose_name='Gói hệ thống (không xoá được)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gói đăng ký',
                'verbose_name_plural': 'Gói đăng ký',
                'ordering': ['user_limit'],
            },
        ),
    ]
