# Generated by Django 5.2.15 on 2026-07-06 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_quotationtemplate'),
        ('users', '0008_systemsettings_maintenance_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='quotation_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='sales.quotationtemplate', verbose_name='Mẫu báo giá áp dụng'),
        ),
    ]
