# Generated by Django 5.2.15 on 2026-07-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_companysettings_default_quotation_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='director_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Họ tên Người đại diện / Giám đốc'),
        ),
        migrations.AddField(
            model_name='company',
            name='director_signature',
            field=models.ImageField(blank=True, null=True, upload_to='company_signatures/', verbose_name='Ảnh chữ ký giám đốc'),
        ),
        migrations.AddField(
            model_name='company',
            name='director_title',
            field=models.CharField(blank=True, default='Giám đốc', max_length=100, verbose_name='Chức danh'),
        ),
        migrations.AddField(
            model_name='company',
            name='stamp_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_stamps/', verbose_name='Ảnh con dấu công ty'),
        ),
    ]
