# Generated by Django 5.2.15 on 2026-07-09 16:50

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_companysettings_active_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='active_modules',
            field=models.JSONField(blank=True, default=users.models.get_default_modules, help_text='Danh sách mã phân hệ được phép sử dụng (vd: crm, sales, products, inventory, production, orders)', verbose_name='Các phân hệ kích hoạt'),
        ),
    ]
