# Generated by Django 5.2.15 on 2026-07-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_companysettings_custom_order_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='default_warranty_content',
            field=models.TextField(blank=True, default='', verbose_name='Nội dung bảo hành mặc định'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='default_warranty_rules',
            field=models.TextField(blank=True, default='', verbose_name='Quy định bảo hành mặc định'),
        ),
    ]
