# Generated by Django 5.2.15 on 2026-07-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_companysettings_default_warranty_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='zalo_app_id',
            field=models.CharField(blank=True, help_text='App ID dùng chung cho các tenant (Lấy từ Zalo Developers).', max_length=100, null=True, verbose_name='System Zalo App ID'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='zalo_app_secret',
            field=models.CharField(blank=True, help_text='App Secret dùng chung cho các tenant.', max_length=255, null=True, verbose_name='System Zalo App Secret'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='zalo_webhook_secret',
            field=models.CharField(blank=True, help_text='Mac Key dùng chung để xác minh webhook từ Zalo.', max_length=255, null=True, verbose_name='System Zalo Webhook Secret'),
        ),
    ]
