# Generated by Django 5.2.16 on 2026-07-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_systemsettings_zalo_app_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='facebook_app_id',
            field=models.CharField(blank=True, help_text='App ID dùng chung cho các tenant (Lấy từ Meta Developers).', max_length=100, null=True, verbose_name='System Facebook App ID'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='facebook_app_secret',
            field=models.CharField(blank=True, help_text='App Secret dùng chung cho các tenant (Meta Developers).', max_length=255, null=True, verbose_name='System Facebook App Secret'),
        ),
    ]
