# Generated by Django 5.2.16 on 2026-07-15 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_integration', '0006_facebooklead_is_archived_and_more'),
        ('users', '0019_facebook_webhook_secret_system_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facebooklead',
            name='is_starred',
            field=models.BooleanField(default=False, verbose_name='Đánh dấu sao / Khách VIP'),
        ),
        migrations.CreateModel(
            name='FacebookLeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='facebook_integration.facebooklead', verbose_name='Hội thoại')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên ghi chú')),
            ],
            options={
                'verbose_name': 'Ghi chú nội bộ hội thoại',
                'verbose_name_plural': 'Ghi chú nội bộ hội thoại',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacebookLeadTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên nhãn/Tag')),
                ('color', models.CharField(default='#3b82f6', max_length=20, verbose_name='Màu sắc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fb_lead_tags', to='users.company', verbose_name='Công ty')),
            ],
            options={
                'verbose_name': 'Nhãn hội thoại Facebook',
                'verbose_name_plural': 'Nhãn hội thoại Facebook',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='facebooklead',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='leads', to='facebook_integration.facebookleadtag', verbose_name='Nhãn/Tag hội thoại'),
        ),
        migrations.CreateModel(
            name='FacebookQuickReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcut', models.CharField(blank=True, max_length=50, verbose_name='Cú pháp gõ tắt (vd: /stk)')),
                ('title', models.CharField(max_length=100, verbose_name='Tiêu đề mẫu tin')),
                ('content', models.TextField(verbose_name='Nội dung tin nhắn mẫu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fb_quick_replies', to='users.company', verbose_name='Công ty')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Tin nhắn mẫu Facebook',
                'verbose_name_plural': 'Tin nhắn mẫu Facebook',
                'ordering': ['title'],
            },
        ),
    ]
