# Generated by Django 5.2.15 on 2026-07-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Chờ sản xuất'), ('in_progress', 'Đang sản xuất'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], db_index=True, default='pending', max_length=20, verbose_name='Trạng thái')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu sản xuất')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc dự kiến')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lệnh sản xuất',
                'verbose_name_plural': 'Lệnh sản xuất',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=150, verbose_name='Tên công đoạn')),
                ('sequence', models.PositiveSmallIntegerField(default=1, help_text='Số thứ tự thực hiện trong lệnh sản xuất.', verbose_name='Thứ tự')),
                ('status', models.CharField(choices=[('pending', 'Chờ thực hiện'), ('in_progress', 'Đang thực hiện'), ('done', 'Hoàn thành')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm bắt đầu')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm hoàn thành')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú công đoạn')),
            ],
            options={
                'verbose_name': 'Công đoạn sản xuất',
                'verbose_name_plural': 'Công đoạn sản xuất',
                'ordering': ['production_order', 'sequence'],
            },
        ),
    ]
