# Generated by Django 5.2.15 on 2026-07-04 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('production', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='users.company', verbose_name='Công ty'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='orders.order', verbose_name='Đơn hàng'),
        ),
        migrations.AddField(
            model_name='productionstep',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_production_steps', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên phụ trách'),
        ),
        migrations.AddField(
            model_name='productionstep',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='production.productionorder', verbose_name='Lệnh sản xuất'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='production_order_end_date_gte_start_date'),
        ),
        migrations.AddConstraint(
            model_name='productionstep',
            constraint=models.CheckConstraint(condition=models.Q(('started_at__isnull', True), ('completed_at__isnull', True), ('completed_at__gte', models.F('started_at')), _connector='OR'), name='production_step_completed_at_gte_started_at'),
        ),
    ]
