# Generated by Django 5.2.15 on 2026-07-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='production_order_code',
            field=models.CharField(blank=True, db_index=True, help_text='Format: [PREFIX]-LSX-[YYYYMMDD]-[SEQ]', max_length=50, null=True, verbose_name='Mã lệnh sản xuất'),
        ),
    ]
