# Generated by Django 5.2.15 on 2026-07-20 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_inventorytransaction_unique_transaction_code_per_company'),
        ('production', '0003_productionorder_production_order_code'),
        ('users', '0021_companysettings_pipeline_status_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Tên nhà máy')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ nhà máy')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factories', to='users.company', verbose_name='Công ty')),
                ('linked_warehouse', models.ForeignKey(blank=True, help_text='Kho vật tư mặc định cho nhà máy này', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_factories', to='inventory.warehouse', verbose_name='Kho liên kết')),
            ],
            options={
                'verbose_name': 'Nhà máy',
                'verbose_name_plural': 'Nhà máy',
            },
        ),
        migrations.AddField(
            model_name='productionorder',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='production.factory', verbose_name='Nhà máy thực hiện'),
        ),
        migrations.AddConstraint(
            model_name='factory',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_factory_per_company'),
        ),
    ]
