# Generated by Django 5.2.15 on 2026-07-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_auto_assign_target',
            field=models.BooleanField(default=False, help_text='Vai trò này được nhận khách từ chức năng phân bổ tự động', verbose_name='Nhận khách tự động'),
        ),
    ]
