# Generated by Django 5.2.15 on 2026-07-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_department_id_department_user_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Khóa toàn bộ chức năng thêm/sửa/xóa dữ liệu của các doanh nghiệp, chỉ cho phép đọc và truy cập hệ thống.', verbose_name='Chế độ bảo trì dữ liệu'),
        ),
    ]
