# Generated by Django 5.2.15 on 2026-07-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_companysettings_quotation_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='default_quotation_terms',
            field=models.TextField(blank=True, default='', verbose_name='Ghi chú & Điều khoản báo giá mặc định'),
        ),
    ]
