# Generated by Django 5.2.15 on 2026-07-09 03:06

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_company_director_name_company_director_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='active_modules',
            field=models.JSONField(blank=True, default=users.models.get_default_modules, help_text='Danh sách mã phân hệ được phép sử dụng (vd: crm, sales, inventory, production, orders)', verbose_name='Các phân hệ kích hoạt'),
        ),
    ]
