# Generated by Django 5.2.15 on 2026-07-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_companysettings_active_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='custom_order_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiêu đề mẫu in Đơn hàng'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='custom_quotation_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiêu đề mẫu in Báo giá'),
        ),
    ]
