# Generated by Django 5.2.16 on 2026-07-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_facebook_oauth_app_config_and_token_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='facebook_webhook_secret',
            field=models.CharField(blank=True, help_text='Mã xác thực webhook hệ thống.', max_length=255, null=True, verbose_name='Facebook Webhook Verify Token chung'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='facebook_app_secret',
            field=models.CharField(blank=True, help_text='App Secret mặc định của ứng dụng Facebook hệ thống.', max_length=255, null=True, verbose_name='Facebook App Secret chung'),
        ),
    ]
