# Generated by Django 5.2.16 on 2026-07-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_facebook_webhook_secret_system_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_sales_department',
            field=models.BooleanField(default=False, help_text='Bật để tính doanh số của phòng ban này vào báo cáo Sales Tốt/Yếu nhất.', verbose_name='Thống kê Doanh số Sales'),
        ),
    ]
