# Generated by Django 5.2.16 on 2026-07-20 10:12

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_department_is_sales_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='pipeline_status_labels',
            field=models.JSONField(blank=True, default=users.models.get_default_pipeline_labels, verbose_name='Tên tùy chỉnh các trạng thái Pipeline'),
        ),
    ]
