# Generated by Django 5.2.16 on 2026-07-21 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_companysettings_pipeline_status_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=30, verbose_name='Tiền tố mã (vd: DH, EXP, LSX)')),
                ('date_str', models.CharField(max_length=8, verbose_name='Ngày (DDMMYYYY)')),
                ('last_seq', models.PositiveIntegerField(default=0, verbose_name='Số thứ tự cuối cùng đã cấp')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='users.company', verbose_name='Công ty')),
            ],
            options={
                'verbose_name': 'Bộ đếm số thứ tự',
                'verbose_name_plural': 'Bộ đếm số thứ tự',
                'indexes': [models.Index(fields=['company', 'prefix', 'date_str'], name='users_compa_company_97783c_idx')],
                'unique_together': {('company', 'prefix', 'date_str')},
            },
        ),
    ]
