# Generated by Django 5.2.16 on 2026-07-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_add_company_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='inactive_days_threshold',
            field=models.PositiveIntegerField(default=0, help_text='Điền 0 để tắt chức năng tự động đánh dấu khách ngủ đông.', verbose_name='Số ngày tính là khách ngủ đông'),
        ),
    ]
