# Generated by Django 5.2.16 on 2026-07-24 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_factory_productionorder_factory_and_more'),
        ('users', '0023_companysettings_inactive_days_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='factory',
            field=models.ForeignKey(blank=True, help_text='Nếu phòng ban này thuộc một nhà máy sản xuất, hãy chọn nhà máy tương ứng.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='production.factory', verbose_name='Nhà máy trực thuộc'),
        ),
    ]
