# Generated by Django 5.2.16 on 2026-07-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_department_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='is_website_integration_active',
            field=models.BooleanField(default=False, help_text='Nếu tắt, CRM sẽ từ chối mọi yêu cầu gửi dữ liệu khách hàng từ Website', verbose_name='Kích hoạt nhận dữ liệu Website'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='website_api_key',
            field=models.CharField(blank=True, help_text='Token bảo mật để kết nối dữ liệu từ Website về CRM', max_length=64, null=True, verbose_name='Mã API Website (Webhook)'),
        ),
    ]
